services:
  postgres:
    image: postgres:17.1
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: postgres-gamebox
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres:
      